# Лабораторная работа №1 | Решение заданий для выполнения

1. Загрузить данные из файла в виде массива numpy типа int32, используя np.loadtxt. Вывести на экран первые 5 строк массива.

In [10]:
import numpy as np

# Путь к загруженному файлу
file_path = 'minutes_n_ingredients2.csv'

# Загрузка данных из файла в виде массива numpy типа int32
data = np.loadtxt(file_path, delimiter=',', dtype=np.int32, skiprows=1)

# Вывод первых 5 строк массива
print(data[:5])


[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [162911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [14]:
data_columns = data[:, 1:]

# Вычисление статистических значений для каждого столбца
mean_values = np.mean(data_columns, axis=0)
min_values = np.min(data_columns, axis=0)
max_values = np.max(data_columns, axis=0)
median_values = np.median(data_columns, axis=0)

# Вывод результатов
print("Средние значения по столбцам:", mean_values)
print("Минимальные значения по столбцам:", min_values)
print("Максимальные значения по столбцам:", max_values)
print("Медианы по столбцам:", median_values)

Средние значения по столбцам: [2.1601398e+04 9.0552800e+00]
Минимальные значения по столбцам: [0 1]
Максимальные значения по столбцам: [2147483647         39]
Медианы по столбцам: [40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля q0.75 .

In [16]:
# Извлечение столбца `minutes`
minutes = data[:, 1]

# Вычисление квантиля 0.75 для `minutes`
q75 = np.percentile(minutes, 75)

# Ограничение значений в `minutes` значением квантиля
minutes_clipped = np.clip(minutes, None, q75)

# Обновление данных в массиве
data[:, 1] = minutes_clipped

# Вывод первых 5 строк для проверки
print(data[:5])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [162911     60     14]]


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [18]:
# Подсчет количества рецептов с нулевой продолжительностью
num_zero_minutes = np.sum(data[:, 1] == 0)
print("Количество рецептов с нулевой продолжительностью:", num_zero_minutes)

# Замена нулевых значений на 1
data[data[:, 1] == 0, 1] = 1

# Проверка результата
num_zero_minutes_after = np.sum(data[:, 1] == 0)
print("Количество рецептов с нулевой продолжительностью после замены:", num_zero_minutes_after)


Количество рецептов с нулевой продолжительностью: 0
Количество рецептов с нулевой продолжительностью после замены: 0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [19]:
# Извлечение столбца с названиями рецептов (предполагается, что это первый столбец)
recipes = data[:, 0]

# Подсчет количества уникальных рецептов
num_unique_recipes = np.unique(recipes).size

print("Количество уникальных рецептов:", num_unique_recipes)


Количество уникальных рецептов: 98252


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [20]:
# Извлечение столбца с количеством ингредиентов (предполагается, что это второй столбец)
num_ingredients = data[:, 2]

# Нахождение уникальных значений и их количества
unique_ingredients, counts = np.unique(num_ingredients, return_counts=True)

# Вывод результатов
print("Количество различных значений количества ингредиентов:", unique_ingredients.size)
print("Уникальные значения и их количество:")
for value, count in zip(unique_ingredients, counts):
    print(f"Значение: {value}, Количество: {count}")


Количество различных значений количества ингредиентов: 37
Уникальные значения и их количество:
Значение: 1, Количество: 13
Значение: 2, Количество: 926
Значение: 3, Количество: 2895
Значение: 4, Количество: 5515
Значение: 5, Количество: 7913
Значение: 6, Количество: 9376
Значение: 7, Количество: 10628
Значение: 8, Количество: 10951
Значение: 9, Количество: 10585
Значение: 10, Количество: 9591
Значение: 11, Количество: 8297
Значение: 12, Количество: 6605
Значение: 13, Количество: 4997
Значение: 14, Количество: 3663
Значение: 15, Количество: 2595
Значение: 16, Количество: 1767
Значение: 17, Количество: 1246
Значение: 18, Количество: 790
Значение: 19, Количество: 573
Значение: 20, Количество: 376
Значение: 21, Количество: 217
Значение: 22, Количество: 161
Значение: 23, Количество: 105
Значение: 24, Количество: 69
Значение: 25, Количество: 50
Значение: 26, Количество: 28
Значение: 27, Количество: 16
Значение: 28, Количество: 16
Значение: 29, Количество: 12
Значение: 30, Количество: 12
Знач

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [21]:
# Создание маски для рецептов с не более чем 5 ингредиентами
mask = data[:, 2] <= 5

# Создание новой версии массива с использованием маски
filtered_data = data[mask]

# Вывод первых 5 строк отфильтрованного массива
print(filtered_data[:5])


[[446597     15      5]
 [204134      5      3]
 [ 25623      6      4]
 [484223     18      4]
 [ 63150     65      4]]


8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [22]:
# Вычисление среднего количества ингредиентов на минуту для каждого рецепта
ingredients_per_minute = data[:, 2] / data[:, 1]

# Нахождение максимального значения
max_ingredients_per_minute = np.max(ingredients_per_minute)

print("Максимальное среднее количество ингредиентов на минуту:", max_ingredients_per_minute)


Максимальное среднее количество ингредиентов на минуту: 24.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [23]:
# Сортировка рецептов по продолжительности в порядке убывания
sorted_indices = np.argsort(data[:, 1])[::-1]
sorted_data = data[sorted_indices]

# Выбор топ-100 рецептов
top_100_recipes = sorted_data[:100]

# Вычисление среднего количества ингредиентов для топ-100 рецептов
average_ingredients_top100 = np.mean(top_100_recipes[:, 2])

print("Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью:", average_ingredients_top100)


Среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью: 9.75


10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [24]:
import random

# Генерация 10 случайных индексов
random_indices = random.sample(range(data.shape[0]), 10)

# Выбор случайных рецептов
random_recipes = data[random_indices]

# Вывод информации о случайных рецептах
for recipe in random_recipes:
    print("Название:", recipe[0])
    print("Продолжительность (минуты):", recipe[1])
    print("Количество ингредиентов:", recipe[2])
    print("-" * 20)


Название: 252594
Продолжительность (минуты): 50
Количество ингредиентов: 6
--------------------
Название: 85080
Продолжительность (минуты): 30
Количество ингредиентов: 5
--------------------
Название: 347346
Продолжительность (минуты): 48
Количество ингредиентов: 11
--------------------
Название: 453991
Продолжительность (минуты): 5
Количество ингредиентов: 4
--------------------
Название: 450374
Продолжительность (минуты): 65
Количество ингредиентов: 12
--------------------
Название: 223225
Продолжительность (минуты): 10
Количество ингредиентов: 3
--------------------
Название: 43932
Продолжительность (минуты): 65
Количество ингредиентов: 8
--------------------
Название: 454927
Продолжительность (минуты): 15
Количество ингредиентов: 20
--------------------
Название: 40849
Продолжительность (минуты): 30
Количество ингредиентов: 17
--------------------
Название: 156623
Продолжительность (минуты): 65
Количество ингредиентов: 6
--------------------


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [27]:
# Вычисление среднего количества ингредиентов
average_ingredients = np.mean(data[:, 2])

# Подсчет количества рецептов с количеством ингредиентов меньше среднего
num_recipes_below_average = np.sum(data[:, 2] < average_ingredients)

# Вычисление процента таких рецептов
percentage_below_average = (num_recipes_below_average / data.shape[0]) * 100

print("Процент рецептов с количеством ингредиентов меньше среднего:", percentage_below_average, "%")


Процент рецептов с количеством ингредиентов меньше среднего: 58.802 %


12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [28]:
# Создание маски для "простых" рецептов
simple_mask = (data[:, 1] <= 20) & (data[:, 2] <= 5)

# Создание столбца с метками "простой" (1) или "не простой" (0)
simple_column = simple_mask.astype(int)

# Добавление столбца к датасету
data_with_simple = np.column_stack((data, simple_column))

# Вывод первых 5 строк нового датасета
print(data_with_simple[:5])


[[127244     60     16      0]
 [ 23891     25      7      0]
 [ 94746     10      6      0]
 [ 67660      5      6      0]
 [162911     60     14      0]]


13. Выведите процент "простых" рецептов в датасете

In [29]:
# Подсчет количества "простых" рецептов
num_simple_recipes = np.sum(data_with_simple[:, -1])

# Вычисление процента "простых" рецептов
percentage_simple = (num_simple_recipes / data_with_simple.shape[0]) * 100

print("Процент 'простых' рецептов:", percentage_simple)


Процент 'простых' рецептов: 9.552


14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [31]:
# Создание масок для каждой группы
short_mask = data[:, 1] < 10
standard_mask = (data[:, 1] >= 10) & (data[:, 1] < 20)
long_mask = data[:, 1] >= 20

# Определение максимального количества рецептов в группе
max_recipes_per_group = min(np.sum(short_mask), np.sum(standard_mask), np.sum(long_mask))

# Выбор рецептов из каждой группы
short_recipes = data[short_mask][:max_recipes_per_group]
standard_recipes = data[standard_mask][:max_recipes_per_group]
long_recipes = data[long_mask][:max_recipes_per_group]

# Создание трехмерного массива
grouped_recipes = np.stack((short_recipes, standard_recipes, long_recipes))

# Вывод формы полученного массива
print("Форма трехмерного массива:", grouped_recipes.shape)


Форма трехмерного массива: (3, 7588, 3)
